version: '3'
services:
  mcsm-daemon-cluster1:
    container_name: mcsm-daemon-cluster1
    hostname: mcsm-daemon-cluster1
    image: eterluu/mcsm-daemon:latest
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '8'
          memory: 48G
        reservations:
          cpus: '8'
          memory: 48G
    depends_on:
      - minecraft-db
      - minecraft-pool
      - minecraft-redis
    environment:
      - PUID=25565
      - PGID=25565
    ports:
      - "24444:24444"
      - "25565-25567:25565-25567"
      - "19132:19132/udp"
    volumes:
      - /srv/minecraft/mcsm-daemon-cluster1:/srv/minecraft/servers
      - /srv/mcsm/mcsm-daemon-cluster1:/opt/mcsmanager/daemon/data
      # - /srv/minecraft/maps:/srv/minecraft/maps
    networks:
      - minecraft-waterfall
      - default
    # tty: true
  minecraft-db:
    container_name: minecraft-db
    hostname: minecraft-db
    image: mariadb:10.7
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          cpus: '2'
          memory: 1G
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "7000:3306"
    volumes:
      - /srv/db/minecraft_db:/var/lib/mysql
    networks:
      - minecraft-database
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --innodb-buffer-pool-size=2G, --log-warnings=0, --max_connections=2000]
    # tty: true
  minecraft-pool:
    container_name: minecraft-pool
    hostname: minecraft-pool
    image: mariadb:10.7
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '4'
          memory: 9G
        reservations:
          cpus: '1'
          memory: 6G
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "7001:3306"
    volumes:
      - /srv/db/minecraft_pool:/var/lib/mysql
    networks:
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --innodb-buffer-pool-size=9G, --log-warnings=0, --max_connections=2000]
    # tty: true
  minecraft-redis:
    container_name: minecraft-redis
    hostname: minecraft-redis
    image: bitnami/redis:latest
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    networks:
      - default
    # tty: true
networks:
  minecraft-waterfall:
    name: minecraft-waterfall
    external: true
  minecraft-database:
    name: minecraft-database
    external: true