version: '0.1'
services:
  mcsm-daemon:
    container_name: mcsm-daemon
    image: eterluu/mcsm-daemon:latest
    mem_limit: 32g
    memswap_limit: 32g
    restart: always
    ports:
      - "24444:24444"
    volumes:
      - /var/mcsm:/srv
  mcsm-db:
    container_name: mcsm-db
    image: mariadb:10.7
    mem_limit: 3g
    memswap_limit: 3g
    restart: always
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "7000:3306"
    volumes:
      - /var/db/mcsm_db:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --innodb-buffer-pool-size=2G, --log-warnings=0, --max_connections=2000]
