version: '3'
services:
  mcsm-daemon:
    container_name: mcsm-daemon
    image: eterluu/mcsm-daemon:latest
    mem_limit: 48g
    memswap_limit: 48g
    restart: always
    environment:
      - PUID=25565
      - PGID=25565
    ports:
      - "24444:24444"
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - /srv/minecraft/servers:/srv/minecraft/servers
      - /srv/mcsm/daemon:/opt/mcsmanager/daemon/data
  minecraft-db:
    image: mariadb:10.7
    mem_limit: 3g
    memswap_limit: 3g
    container_name: minecraft-db
    restart: always
    environment:
      - LANG=C.UTF-8
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=
    # ports:
    #   - "3306:3306"
    volumes:
      - /srv/db/minecraft_db:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --innodb-buffer-pool-size=2G, --log-warnings=0, --max_connections=2000]
networks:
  minecraft-waterfall:
    name: minecraft-waterfall
    external: true