version: '3'
services:
  mcsm-web:
    container_name: mcsm-web
    image: eterluu/mcsm-web:latest
    mem_limit: 1G
    memswap_limit: 1G
    restart: always
    environment:
      - PUID=25565
      - PGID=25565
    ports:
      - "23333:23333"
    volumes:
      - /srv/mcsm/web:/opt/mcsmanager/web/data