version: '3'
services:
  mcsm-web:
    container_name: mcsm-web
    image: eterluu/mcsm-web:latest
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.1'
          memory: 500M
    environment:
      - PUID=25565
      - PGID=25565
    ports:
      - "23333:23333"
    volumes:
      - /srv/mcsm/web:/opt/mcsmanager/web/data
    # tty: true